### PR TITLE
added a dockerfile

### PR DESCRIPTION
**Pull request by robbarnsley**

### CODE REVIEW

**Comment by riccardodimaria** [comment]
`fts-analysis` should be moved into `ESCAPE-WP2/containers` before merging this PR.

**Comment by rizart** [comment]
> `fts-analysis` should be moved into `ESCAPE-WP2/containers` before merging this PR.

It's not `fts-analysis` that should be moved, we just need to cancel this pull request and create a new folder on `ESCAPE-WP2/containers/misc` with the relevant docker configs for this code.

**Comment by robbarnsley** [comment]
This seems like an odd architecture choice to me. I will, of course, do as you wish, but could someone explain why? Is it not best to retain the Dockerfile in the repository it relates to? By amalgamating it into a repository of containers it obfuscates its usage which is otherwise obvious by placing it in the same repository.

From a development perspective, if I change something in fts-analysis that has side effects on the environment, I then have to clone another repository to change the corresponding Dockerfile. This is not great from a version traceability perspective.

Not to mention that having a repository of containers mixes the versioning history together for multiple standalone projects.

**Comment by riccardodimaria** [comment]
This is exactly why I wanted it moved to `ESCAPE-WP2/containers`. I am not following `fts-analysis` repo/work at all atm. But in principle, all pieces of SW that have been docker-ised should be self-contained in a sub-repo `your-name-choice` so that, when someone wants to fetch it, it can be found in `ESCAPE-WP2/containers/your-name-choice`. This will allow us to host other repo within `ESCAPE-WP2`, e.g. `ESCAPE-WP2/puppet`, `ESCAPE-WP2/k8s` (that could read from `containers`), and so on. I am not sure I am following you @robbarnsley on the problematics you see in this approach.
I am not also following what are @rizart plans wrt FTS.

**Comment by rizart** [comment]
@robbarnsley , you are right, it's better to have one point of update for both the code and the dockerfile, let's proceed like this with this repo. We can still utilize the containers repo for code that we do not control and for code that a dockerized environment does not already exist. I am merging this pull request now.

**Pull request merged**
